services:
  - type: web
    name: recolekt-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && chmod +x install_ffmpeg.sh && ./install_ffmpeg.sh"
    startCommand: "python app.py"
    envVars:
      - key: GCS_BUCKET
        value: recolekt-storage
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/gcp/service-account.json
      - key: CRAWLBASE_TOKEN
        value: l-a9kEqGcONKdgYJfKIQuw  # Replace with your actual token
    autoDeploy: true
