services:
  - type: web
    name: recolekt-frontend
    env: node
    build:
      env:
        - NPM_CONFIG_PRODUCTION=false  # Ensure devDependencies are installed
    plan: free
    startCommand: npm run start  # or `vite preview` to run the build
