services:
  - type: web
    name: recolekt-backend
    env: python
    build:
      env:
        - FFmpeg: https://github.com/jonathanong/heroku-buildpack-ffmpeg
    plan: free
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 app:app
