"""
Generic data formatting helpers for reels.

This module is intentionally LIGHT on domain logic:
- It does NOT parse captions/transcripts.
- It assumes an LLM has already produced the structured fields:
  - summary (bilingual)
  - recipe (bilingual, any language) if present
  - workout, finance, etc. if present

The goal here is to:
- Safely json-load text fields coming from the DB.
- Normalize recipe objects via recipe_formatters.normalize_recipe.
- Build a consistent "summary" block the frontend can rely on.
"""

import json
import logging
from typing import Any, Dict, List, Tuple

from .recipe_formatters import normalize_recipe

logger = logging.getLogger("formatters")


# ==================== GENERIC HELPERS ====================

def json_loads_maybe(v: Any, default=None):
    """
    Best-effort JSON parser:
    - If v is already a dict or list, return as is.
    - If v is a string, try json.loads, otherwise return default.
    """
    if v is None:
        return default
    if isinstance(v, (dict, list)):
        return v
    if isinstance(v, str):
        s = v.strip()
        if not s:
            return default
        try:
            return json.loads(s)
        except Exception:
            return default
    return default


def coerce_title_to_str(current_title: Any) -> str:
    """
    Normalize title into a simple string, handling:
    - plain string
    - nested structures with "english.title" or "title"
    """
    if current_title is None:
        return ""
    if isinstance(current_title, str):
        return current_title.strip()

    if isinstance(current_title, dict):
        eng = current_title.get("english")
        if isinstance(eng, dict):
            t = eng.get("title")
            if isinstance(t, str):
                return t.strip()
        t = current_title.get("title")
        if isinstance(t, str):
            return t.strip()

    try:
        return str(current_title).strip()
    except Exception:
        return ""


def extract_english_preview_and_title(
    summary_text: Any,
    current_title: Any = None
) -> Tuple[str, str]:
    """
    Given a "summary_text" field, return:
    - english_preview: a short summary string for listing cards.
    - title: a string title (prefer existing, fall back to English title).

    summary_text can be:
    - a plain English string (legacy).
    - a dict with "english" and "original" blocks.
    """
    title = coerce_title_to_str(current_title)
    english_preview = ""

    # Legacy: summary_text is a simple English string
    if isinstance(summary_text, str):
        english_preview = summary_text.strip()
        return english_preview, title

    if not isinstance(summary_text, dict):
        return english_preview, title

    eng = summary_text.get("english", None)
    if isinstance(eng, dict):
        english_preview = (eng.get("summary") or eng.get("text") or "").strip()
        if not title:
            t = eng.get("title")
            if isinstance(t, str):
                title = t.strip()
        return english_preview, title

    if isinstance(eng, str):
        english_preview = eng.strip()
        if not title:
            maybe_title = summary_text.get("title")
            if isinstance(maybe_title, str):
                title = maybe_title.strip()
        return english_preview, title

    # Fallback: try top-level fields on the dict
    english_preview = (summary_text.get("summary") or summary_text.get("text") or "").strip()
    if not title:
        maybe_title = summary_text.get("title")
        if isinstance(maybe_title, str):
            title = maybe_title.strip()

    return english_preview, title


def build_bilingual_summary_object(
    summary_title: Any,
    summary_text: Any,
    bullets: Any,
    hashtags: Any,
    emojis: Any,
    caption: str,
) -> Dict[str, Any]:
    """
    Build a bilingual summary object when only an English string was stored.

    This is primarily a BACKWARDS COMPATIBILITY path:
    - Newer content should already have the full bilingual "summary" object
      generated by the LLM.
    """
    title_str = coerce_title_to_str(summary_title)
    summary_str = summary_text.strip() if isinstance(summary_text, str) else ""

    bullets_list = bullets if isinstance(bullets, list) else []
    hashtags_list = hashtags if isinstance(hashtags, list) else []
    emojis_list = emojis if isinstance(emojis, list) else []

    # Simple original-language approximation: use caption as "original summary" if present.
    # We intentionally keep this logic very light and language-agnostic.
    orig_title = title_str or (caption[:56] if caption else "")
    orig_summary = caption[:320].strip() if caption else summary_str

    return {
        "english": {
            "title": title_str,
            "summary": summary_str,
            "headlines": bullets_list,
            "hashtags": hashtags_list,
            "emojis": emojis_list,
        },
        "original": {
            "title": orig_title,
            "summary": orig_summary,
            "headlines": bullets_list,
            "hashtags": hashtags_list,
            "emojis": emojis_list,
        }
    }


# ==================== RESPONSE FORMATTERS ====================

def format_reel_response(row_dict: Dict[str, Any]) -> Dict[str, Any]:
    """
    Normalize a single reel DB row into a frontend-ready dict.

    This function is intentionally generic and supports ANY reel type:
    - Food (recipes)
    - Workouts
    - Finance tips
    - Life hacks
    - Etc.

    It assumes the heavy lifting (structuring & translation) has been done
    by the LLM and only:
    - json-loads text fields,
    - normalizes recipe objects,
    - ensures the "summary" block has a consistent shape.
    """
    caption = row_dict.get("caption") or ""

    # Parse nested JSON blobs if they are stored as text
    row_dict["recipe"] = json_loads_maybe(row_dict.get("recipe"), default=row_dict.get("recipe"))
    row_dict["workout"] = json_loads_maybe(row_dict.get("workout"), default=row_dict.get("workout"))

    # Normalize recipe if present (language-agnostic), using CAPTION
    if isinstance(row_dict.get("recipe"), dict):
        row_dict["recipe"] = normalize_recipe(row_dict["recipe"], caption=caption)

    # Handle summary / title / bilingual structure
    summary_text_raw = row_dict.get("summary_text")
    summary_text = json_loads_maybe(summary_text_raw, default=summary_text_raw)

    bullets = json_loads_maybe(row_dict.get("summary_bullets"), default=row_dict.get("summary_bullets"))
    hashtags = json_loads_maybe(row_dict.get("summary_hashtags"), default=row_dict.get("summary_hashtags"))
    emojis = json_loads_maybe(row_dict.get("summary_emojis"), default=row_dict.get("summary_emojis"))

    if not isinstance(bullets, list):
        bullets = []
    if not isinstance(hashtags, list):
        hashtags = []
    if not isinstance(emojis, list):
        emojis = []

    summary_title = row_dict.get("summary_title")

    # If summary_text is not already a bilingual dict, wrap it.
    if not isinstance(summary_text, dict):
        bilingual = build_bilingual_summary_object(
            summary_title=summary_title,
            summary_text=summary_text if isinstance(summary_text, str) else "",
            bullets=bullets,
            hashtags=hashtags,
            emojis=emojis,
            caption=caption,
        )
        summary_text = bilingual

    english_preview, summary_title_str = extract_english_preview_and_title(summary_text, summary_title)
    if not summary_title_str and caption:
        summary_title_str = caption[:50]

    # Persist normalized fields back into the row dict
    row_dict["summary_title"] = summary_title_str
    row_dict["summary_text"] = summary_text
    row_dict["summary_bullets"] = bullets
    row_dict["summary_hashtags"] = hashtags
    row_dict["summary_emojis"] = emojis

    # Build a flattened "summary" object for the frontend
    row_dict["summary"] = {
        "category": row_dict.get("summary_category", "General"),
        "title": summary_title_str,
        "topic": row_dict.get("summary_topic", ""),
        "summary": english_preview if english_preview else "",
        "bullets": bullets,
        "hashtags": hashtags,
        "emojis": emojis,
        "bilingual": summary_text if isinstance(summary_text, dict) else None,
    }

    # Media URLs
    thumb = row_dict.get("preview_thumbnail")
    row_dict["gcs_urls"] = {
        "preview_thumbnail": thumb if thumb else None
    }

    # Generic metadata
    row_dict["author_name"] = row_dict.get("author_name") or "Unknown"
    row_dict.pop("preview_thumbnail", None)

    return row_dict


def format_reels_list(db_rows: List[Any]) -> List[Dict[str, Any]]:
    """
    Normalize a list of DB rows into frontend-ready reels.
    """
    transformed_rows: List[Dict[str, Any]] = []

    for row in db_rows:
        if hasattr(row, "keys"):
            row_dict = dict(row)
        elif hasattr(row, "as_dict"):
            row_dict = row.as_dict()
        else:
            continue

        formatted = format_reel_response(row_dict)
        transformed_rows.append(formatted)

    return transformed_rows
